### ISSUE TITLE
[Recommender] Setting Age Range

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/recommender#32] opened 2015-11-18 13:18 UTC
In the profile the user can set an age range. As soon as i disclose the age range to the recommender i do not get any results any more (independent of the age set). Could you please take a look?

**Comment by hziak** [comment] 2015-11-18 13:27
actually it should work correctly.
if you set it to AgeRange:2 you should get result.
The thing is that at the moment we have no provider that has an AgeRange lower than 2

**Comment by chseifert** [comment] 2015-11-18 13:29
Confirmed that it does not work (chose all the different age ranges in the extension), on stable server.
Related to https://github.com/EEXCESS/eexcess/issues/11

**Comment by hziak** [comment] 2015-11-18 13:34
cant confirm that:
{"numResults":10,
"ageRange":0,
    "contextKeywords":[{
        "text":"napoleon"
    }]
}
gave me no partners on the stable
{"numResults":10,
"ageRange":2,
    "contextKeywords":[{
        "text":"napoleon"
    }]
}
gave me all partners

so perhabs you can send me the query you send?

**Comment by schloett** [comment] 2015-11-18 13:36
0 results for all age ranges is a bug of the extension (ageRange is always set to 0).

**Comment by schloett** [comment] 2015-11-18 14:00
Fixed it in the extension (new version 1.3.2 should be available within the next 60 minutes). 
However, for me the meaning of the values is unclear: what is 0, what is 1, what is 2? The profile page in the extension states 'child', 'young adult', 'adult'. Furthermore, how is suitable partner content defined? How does 'young adult' differ from 'adult' (if this is the correct interpretation of 1 and 2 anyhow). Is the content in Europeana not suitable for children (at least partially?).

**Comment by hziak** [comment] 2015-11-18 14:32
i agree, but that was agreed in the meeting in passau as final solution.
 The birthdate, which would have been more flexible, seemed to be too sensitive.  Although it was allready covered by the first age source selection algorithm. 
Furthermore, it is not possible to filter on result level, since the information of the items is missing, so we have to filter on partner level.
Part of the Europeana content might not be appropriate for children, so at least at the moment it is marked as adult content. 

The fuzziness of the definition "young adult" might even have a legal upside since not every country has the same age limits.

**Comment by chseifert** [comment] 2015-11-18 14:35
I think the decision on the 3 levels and the filtering is not a problem. Just the transparency for client developers is.

**Comment by mgrani** [comment] 2015-11-18 15:07
As a solution one could pass back the properties of the partner systems when querying the document badge. Overall i find it a minor issue.

**Comment by chseifert** [comment] 2015-11-19 10:56
Tested and works (with age range either undefined or set to 2 i get results). This is the expected behaviour as we don't have any resources for lower age levels.

**Closed as completed by chseifert** 2015-11-19 10:56 UTC
Labels: bug
